python -u run.py \
  --task_name anomaly_detection_custom \
  --is_training 1 \
  --root_path ./dataset/ANAM \
  --data_path Normal_uni.csv \
  --model_id ANAM \
  --model TimesNet \
  --data custom \
  --features S \
  --target Cumul_precipitation \
  --freq d \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 16 \
  --d_ff 16  \
  --e_layers 3 \
  --enc_in 1 \
  --c_out 1 \
  --top_k 4 \
  --anomaly_ratio 10 \
  --batch_size 128 \
  --train_epochs 100