python -u run.py \
  --task_name anomaly_detection_custom \
  --is_training 1 \
  --root_path ./dataset/ANAM \
  --data_path Normal_uni.csv \
  --model_id ANAM \
  --model TimesNet \
  --data custom \
  --features S \
  --target Cumul_precipitation \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 64 \
  --d_ff 64 \
  --e_layers 2 \
  --enc_in 31 \
  --c_out 31 \
  --top_k 3 \
  --anomaly_ratio 1 \
  --batch_size 128 \
  --train_epochs 3